"""kakao_place_id

Revision ID: 692f33862f38
Revises: d801741c4d44
Create Date: 2026-05-30 08:13:36.666948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '692f33862f38'
down_revision: Union[str, None] = 'd801741c4d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoints', sa.Column('kakao_place_id', sa.String(length=255), nullable=True))
    op.drop_column('waypoints', 'google_place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoints', sa.Column('google_place_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('waypoints', 'kakao_place_id')
    # ### end Alembic commands ###
