"""add_trip_premium

Revision ID: 78ef8300ba7d
Revises: d801741c4d44
Create Date: 2026-06-03 11:14:10.081169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '78ef8300ba7d'
down_revision: Union[str, None] = 'd801741c4d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_premiums',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_key', sa.String(length=200), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.alter_column('trips', 'visibility',
               existing_type=mysql.ENUM('private', 'link', 'public', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('private', 'link', 'public', name='visibility_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('waypoints', 'transport_mode',
               existing_type=mysql.ENUM('walk', 'car', 'transit', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('walk', 'car', 'transit', name='transport_enum', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waypoints', 'transport_mode',
               existing_type=sa.Enum('walk', 'car', 'transit', name='transport_enum', native_enum=False),
               type_=mysql.ENUM('walk', 'car', 'transit', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('trips', 'visibility',
               existing_type=sa.Enum('private', 'link', 'public', name='visibility_enum', native_enum=False),
               type_=mysql.ENUM('private', 'link', 'public', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_table('trip_premiums')
    # ### end Alembic commands ###
